In [1]:
import pandas as pd

In [3]:
matches = pd.read_csv("epl_matches_stats.csv", index_col=0)

In [4]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,Match Report,NaN,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,Match Report,NaN,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,Match Report,NaN,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,Match Report,NaN,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,Match Report,NaN,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal

In [5]:
matches.shape

(1302, 27)

In [7]:
matches["round"].value_counts()

Matchweek 1     40
Matchweek 16    40
Matchweek 27    40
Matchweek 26    40
Matchweek 24    40
Matchweek 12    40
Matchweek 23    40
Matchweek 2     40
Matchweek 21    40
Matchweek 20    40
Matchweek 19    40
Matchweek 18    40
Matchweek 17    40
Matchweek 22    40
Matchweek 15    40
Matchweek 6     40
Matchweek 14    40
Matchweek 4     40
Matchweek 5     40
Matchweek 3     40
Matchweek 10    40
Matchweek 11    40
Matchweek 13    40
Matchweek 9     40
Matchweek 8     38
Matchweek 25    36
Matchweek 28    36
Matchweek 7     32
Matchweek 35    20
Matchweek 37    20
Matchweek 33    20
Matchweek 36    20
Matchweek 31    20
Matchweek 34    20
Matchweek 30    20
Matchweek 32    20
Matchweek 29    20
Matchweek 38    20
Name: round, dtype: int64

In [8]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes            object
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [9]:
#chaging the data types
matches["date"] = pd.to_datetime(matches["date"])

In [11]:
#new column target is added. 1 for win, 0 for lose
matches["target"] = (matches["result"] == "W").astype("int")

In [12]:
#new column venue_code is added, 1 is for Home and 0 is for Away
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [15]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,target,venue_code
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,10.0,2.0,14.6,1.0,0.0,0.0,2023,Arsenal,1,0
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,19.0,7.0,13.0,0.0,0.0,0.0,2023,Arsenal,1,1
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,14.0,6.0,14.8,0.0,0.0,0.0,2023,Arsenal,1,0
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,22.0,8.0,15.5,1.0,0.0,0.0,2023,Arsenal,1,1
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,22.0,8.0,16.3,1.0,0.0,0.0,2023,Arsenal,1,1

In [16]:
#categorizing the opponent teams
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sot,dist,fk,pk,pkatt,season,team,target,venue_code,opp_code
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,2.0,14.6,1.0,0.0,0.0,2023,Arsenal,1,0,7
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,7.0,13.0,0.0,0.0,0.0,2023,Arsenal,1,1,11
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,6.0,14.8,0.0,0.0,0.0,2023,Arsenal,1,0,2
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,8.0,15.5,1.0,0.0,0.0,2023,Arsenal,1,1,9
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,8.0,16.3,1.0,0.0,0.0,2023,Arsenal,1,1,1

In [18]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [19]:
matches["day_code"] = matches["date"].dt.dayofweek

In [20]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,1.0,0.0,0.0,2023,Arsenal,1,0,7,20,4
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,0.0,0.0,0.0,2023,Arsenal,1,1,11,15,5
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,0.0,0.0,0.0,2023,Arsenal,1,0,2,17,5
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,1.0,0.0,0.0,2023,Arsenal,1,1,9,17,5
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,1.0,0.0,0.0,2023,Arsenal,1,1,1,19,2

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [23]:
train = matches[matches["date"] < '2022-01-01']

In [24]:
train.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,0,19,16,6
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,1,16,15,5
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,1,0,12,5
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,1,0,11,15,5
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,0,1,18,15,5

In [25]:
test = matches[matches["date"] > '2022-01-01']

In [26]:
test.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2.0,0.0,Crystal Palace,...,1.0,0.0,0.0,2023,Arsenal,1,0,7,20,4
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,2.0,Leicester City,...,0.0,0.0,0.0,2023,Arsenal,1,1,11,15,5
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3.0,0.0,Bournemouth,...,0.0,0.0,0.0,2023,Arsenal,1,0,2,17,5
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,1.0,0.0,0.0,2023,Arsenal,1,1,9,17,5
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,1.0,0.0,0.0,2023,Arsenal,1,1,1,19,2

In [27]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [28]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [29]:
preds = rf.predict(test[predictors])

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
error = accuracy_score(test["target"], preds)

In [32]:
error

0.5967741935483871

In [33]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [34]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          442  128
1          247  113

In [35]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.46887966804979253

In [36]:
grouped_matches = matches.groupby("team")

In [37]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [38]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [39]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,15,5,3.333333,0.333333,19.666667,6.000000,16.866667,0.666667,0.000000,0.000000
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,15,5,3.666667,0.000000,22.000000,7.333333,15.866667,0.333333,0.000000,0.000000
8,2021-09-25,12:30,Premier League,Matchweek 6,Sat,Away,W,1.0,0.0,Chelsea,...,12,5,2.000000,0.000000,22.000000,6.333333,15.166667,0.333333,0.000000,0.000000
10,2021-10-03,16:30,Premier League,Matchweek 7,Sun,Away,D,2.0,2.0,Liverpool,...,16,6,0.666667,0.000000,18.666667,4.000000,15.933333,0.333333,0.000000,0.000000
11,2021-10-16,15:00,Premier League,Matchweek 8,Sat,Home,W,2.0,0.0,Burnley,...,15,5,1.000000,0.666667,14.333333,2.333333,16.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,2023-02-15,19:30,Premier League,Matchweek 12,Wed,Away,W,3.0,1.0,Arsenal,...,19,2,2.000000,0.666667,14.333333,5.666667,15.966667,0.666667,0.666667,0.666667
35,2023-02-18,15:00,Premier League,Matchweek 24,Sat,Away,D,1.0,1.0,Nott'ham Forest,...,15,5,2.000000,1.000000,13.333333,5.666667,15.066667,0.666667,0.333333,0.333333
37,2023-02-25,17:30,Premier League,Matchweek 25,Sat,Away,W,4.0,1.0,Bournemouth,...,17,5,2.333333,1.000000,16.000000,6.000000,15.166667,1.000000,0.333333,0.333333
39,2023-03-04,12:30,Premier League,Matchweek 26,Sat,Home,W,2.0,0.0,Newcastle Utd,...,12,5,2.666667,1.000000,17.333333,5.333333,15.133333,1.000000,0.000000,0.000000
40,2023-03-11,17:30,Premier League,Matchweek 27,Sat,Away,W,1.0,0.0,Crystal Palace,...,17,5,2.333333,0.666667,18.000000,4.666667,16.366667,1.666667,0.000000,0.000000

In [40]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [41]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2021-09-11  15:00  Premier League   Matchweek 4
                        5  2021-09-18  15:00  Premier League   Matchweek 5
                        7  2021-09-26  16:30  Premier League   Matchweek 6
                        8  2021-10-02  17:30  Premier League   Matchweek 7
                        9  2021-10-18  20:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 29 2023-02-24  20:00  Premier League  Matchweek 25
                        30 2023-03-01  20:00  Premier League   Matchweek 7
                        31 2023-03-04  15:00  Premier League  Matchweek 26
                        32 2023-03-12  16:30  Premier League  Matchweek 27
                        33 2023-03-18  15:00  Premier League  Matchweek 28

                            day venue result   gf   ga        opponent  ...  \
team                                                                    ...
Arsenal                 4   Sat  Home      W  1.0  0.0    Norwich City  ...
                        5   Sat  Away      W  1.0  0.0         Burnley  ...
                        7   Sun  Home      W  3.0  1.0       Tottenham  ...
                        8   Sat  Away      D  0.0  0.0        Brighton  ...
                        9   Mon  Home      D  2.0  2.0  Crystal Palace  ...
...                         ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 29  Fri  Away      D  1.0  1.0          Fulham  ...
                        30  Wed  Away      L  0.0  2.0       Liverpool  ...
                        31  Sat  Home      W  1.0  0.0       Tottenham  ...
                        32  Sun  Away      L  1.0  2.0   Newcastle Utd  ...
                        33  Sat  Home      L  2.0  4.0    Leeds United  ...

                            hour  day_code  gf_rolling  ga_rolling sh_rolling  \
team
Arsenal                 4     15         5    0.000000    3.000000   9.666667
                        5     15         5    0.333333    2.333333  12.333333
                        7     16         6    0.666667    1.666667  14.666667
                        8     17         5    1.666667    0.333333  18.333333
                        9     20         0    1.333333    0.333333  11.000000
...                          ...       ...         ...         ...        ...
Wolverhampton Wanderers 29    20         4    1.666667    0.666667  12.666667
                        30    20         2    1.000000    1.000000  11.333333
                        31    15         5    0.333333    1.333333   9.000000
                        32    16         6    0.666667    1.000000   6.666667
                        33    15         5    0.666667    1.333333   6.333333

                           sot_rolling dist_rolling fk_rolling pk_rolling  \
team
Arsenal                 4     2.333333    14.833333   0.333333        0.0
                        5     3.000000    14.133333   0.333333        0.0
                        7     3.000000    14.800000   0.666667        0.0
                        8     5.333333    18.433333   0.666667        0.0
                        9     4.000000    19.833333   0.666667        0.0
...                                ...          ...        ...        ...
Wolverhampton Wanderers 29    3.333333    16.766667   0.000000        0.0
                        30    2.333333    16.700000   0.000000        0.0
                        31    2.333333    14.133333   0.000000        0.0
                        32    2.666667    16.700000   0.000000        0.0
                        33    3.333333    17.166667   0.333333        0.0

                            pkatt_rolling
team
Arsenal                 4             0.0
                        5             0.0
                        7             0.0
                        8             0.0
                        9             0.0
...                                   ...
Wolverhampton Wanderers 29            0.0
                        30            0.0
                        31            0.0
                        32            0.0
                        33            0.0

[1233 rows x 40 columns]

In [42]:
matches_rolling = matches_rolling.droplevel('team')

In [43]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,15,5,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.0,0.0
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,15,5,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.0,0.0
7,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,16,6,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.0,0.0
8,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,17,5,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.0,0.0
9,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,20,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,2023-02-24,20:00,Premier League,Matchweek 25,Fri,Away,D,1.0,1.0,Fulham,...,20,4,1.666667,0.666667,12.666667,3.333333,16.766667,0.000000,0.0,0.0
30,2023-03-01,20:00,Premier League,Matchweek 7,Wed,Away,L,0.0,2.0,Liverpool,...,20,2,1.000000,1.000000,11.333333,2.333333,16.700000,0.000000,0.0,0.0
31,2023-03-04,15:00,Premier League,Matchweek 26,Sat,Home,W,1.0,0.0,Tottenham,...,15,5,0.333333,1.333333,9.000000,2.333333,14.133333,0.000000,0.0,0.0
32,2023-03-12,16:30,Premier League,Matchweek 27,Sun,Away,L,1.0,2.0,Newcastle Utd,...,16,6,0.666667,1.000000,6.666667,2.666667,16.700000,0.000000,0.0,0.0
33,2023-03-18,15:00,Premier League,Matchweek 28,Sat,Home,L,2.0,4.0,Leeds United,...,15,5,0.666667,1.333333,6.333333,3.333333,17.166667,0.333333,0.0,0.0

In [44]:
matches_rolling.index = range(matches_rolling.shape[0])

In [45]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [46]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [47]:
error

0.49489795918367346

In [48]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [49]:
combined.head(10)

    actual  predicted       date     team        opponent result
17       0          0 2022-01-23  Arsenal         Burnley      D
18       1          0 2022-02-10  Arsenal          Wolves      W
19       1          0 2022-02-19  Arsenal       Brentford      W
20       1          1 2022-02-24  Arsenal          Wolves      W
21       1          1 2022-03-06  Arsenal         Watford      W
22       1          1 2022-03-13  Arsenal  Leicester City      W
23       0          1 2022-03-16  Arsenal       Liverpool      L
24       1          0 2022-03-19  Arsenal     Aston Villa      W
25       0          0 2022-04-04  Arsenal  Crystal Palace      L
26       0          0 2022-04-09  Arsenal        Brighton      L

In [50]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [51]:
combined["new_team"] = combined["team"].map(mapping)

In [52]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [53]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,0,2023-02-24,Wolverhampton Wanderers,Fulham,D,Wolves,0,0,Fulham,Wolves,D,Fulham
884,0,0,2023-03-01,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
885,1,0,2023-03-04,Wolverhampton Wanderers,Tottenham,W,Wolves,0,0,Tottenham Hotspur,Wolves,L,Tottenham
886,0,0,2023-03-12,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
887,0,0,2023-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United

In [54]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    82
0    76
Name: actual_x, dtype: int64